name: Release

on:
  release:
    types:
      - published
    branches:
      - 'main'

jobs:
  publish:
    name: Release
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Get Package Name (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $path_separator = "\\"
          $latestFile = Get-ChildItem -Path "dist\\" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          Write-Host "Latest file: $latestFile"
          Write-Output "PACKAGE_NAME=dist$path_separator$($latestFile.Name)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Get Package Name (Ubuntu and macOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          path_separator="/"
          latestFile=$(ls -t dist/ | head -n 1)
          echo "Latest file: $latestFile"
          echo "PACKAGE_NAME=dist$path_separator$latestFile" >> $GITHUB_ENV

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --repository pypi ${{ env.PACKAGE_NAME }}